# Generated by Django 5.2.3 on 2025-06-29 16:30

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_completed",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последнее выполнение"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="duration",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(120),
                ],
                verbose_name="Время на выполнение (сек)",
            ),
        ),
        migrations.AddConstraint(
            model_name="habit",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration__lte", 120)),
                name="duration_max_120_seconds",
            ),
        ),
        migrations.AddConstraint(
            model_name="habit",
            constraint=models.CheckConstraint(
                condition=models.Q(("frequency__gte", 1), ("frequency__lte", 7)),
                name="frequency_between_1_and_7",
            ),
        ),
    ]
